// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiPcPuD0CJmzsKR1NSjnvGcAsNq6SUMcM',
    appId: '1:1089453162888:web:94ecd0ee1bd593242b3a3d',
    messagingSenderId: '1089453162888',
    projectId: 'todo-df8b1',
    authDomain: 'todo-df8b1.firebaseapp.com',
    databaseURL: 'https://todo-df8b1-default-rtdb.firebaseio.com',
    storageBucket: 'todo-df8b1.appspot.com',
    measurementId: 'G-1T7EB7GEVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXtEP1GzCb2ttX1Ty_OXM-JgMD8edblyk',
    appId: '1:1089453162888:android:18d49d4cb269eb9a2b3a3d',
    messagingSenderId: '1089453162888',
    projectId: 'todo-df8b1',
    databaseURL: 'https://todo-df8b1-default-rtdb.firebaseio.com',
    storageBucket: 'todo-df8b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBKVQq1RPb7gg4JE9DAuhmy2DPLTirqUsk',
    appId: '1:1089453162888:ios:313397d3e15ca7252b3a3d',
    messagingSenderId: '1089453162888',
    projectId: 'todo-df8b1',
    databaseURL: 'https://todo-df8b1-default-rtdb.firebaseio.com',
    storageBucket: 'todo-df8b1.appspot.com',
    iosBundleId: 'com.example.tryRiverpod',
  );
}
